In [1]:
import pandas as pd
from datetime import datetime as dt
import os
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
import matplotlib.dates as mdates
import datetime as dt
import numpy as np
file = 'data.csv'
df = pd.read_csv(file)
df

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658
...,...,...,...,...,...,...,...,...,...,...,...,...
61895,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
61896,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
61897,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
61898,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN
61899,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa,NaN

In [2]:
del df['countryterritoryCode']
del df['geoId']
del df['day']
df = df.loc[df['month'] != 1]
del df['month']
del df['year']
df = df.dropna(how='any')
dfclean = df.loc[df['cases'] != 0]
dfclean = dfclean.rename(columns = {'dateRep':'Date'})

In [3]:
dfclean['Date'] = pd.to_datetime(dfclean['Date']).dt.strftime('%m/%d/%Y')

In [4]:
country = ['Belgium','Finland','France','Ghana','Egypt','Israel','Iraq','Vietnam','Singapore','Malaysia','United_States_of_America', 'United_Kingdom','Australia','New_Zealand']
final = dfclean.loc[dfclean['countriesAndTerritories'].isin(country)]
final = final.rename(columns = {'countriesAndTerritories': 'Country', 'continentExp': 'continent', 'Cumulative_number_for_14_days_of_COVID-19_cases_per_100000': '14 day cases/100,000', 'popData2019':'population'})

In [5]:
final.to_csv("cleaned_data.csv", index=False, header=True)