In [3]:
# Dependencies
import pandas as pd

In [4]:
file = 'response_measures.csv'
df_response = pd.read_csv(file)
df_response

             Country       Response_measure  date_start    date_end
0            Austria  AdaptationOfWorkplace  2020-03-16  2020-04-13
1            Austria         BanOnAllEvents  2020-11-03         NaN
2            Austria            ClosDaycare  2020-03-16  2020-05-04
3            Austria     ClosDaycarePartial  2020-11-17  2020-12-07
4            Austria               ClosHigh  2020-03-16  2020-09-30
...              ...                    ...         ...         ...
1483  United Kingdom          StayHomeRiskG  2020-03-16  2020-07-05
1484  United Kingdom          StayHomeRiskG  2020-11-05  2020-12-01
1485  United Kingdom          StayHomeRiskG  2021-01-05         NaN
1486  United Kingdom   StayHomeRiskGPartial  2020-07-06  2020-08-01
1487  United Kingdom            Teleworking  2020-03-16         NaN

[1488 rows x 4 columns]

In [5]:
df_response = df_response.dropna(how='any')

In [6]:
country = ['Belgium','Finland','France','Ghana','Egypt','Israel','Iraq','Vietnam','Singapore','Malaysia','United_Kingdom','United_States_of_America']
final_response = df_response.loc[df_response['Country'].isin(country)]
final_response

     Country      Response_measure  date_start    date_end
66   Belgium           ClosDaycare  2020-05-01  2020-06-02
67   Belgium           ClosDaycare  2020-11-12  2020-11-15
69   Belgium              ClosPrim  2020-03-13  2020-05-17
70   Belgium              ClosPrim  2020-11-12  2020-11-16
71   Belgium       ClosPrimPartial  2020-05-18  2020-06-08
..       ...                   ...         ...         ...
471   France         StayHomeOrder  2020-10-28  2020-12-14
472   France  StayHomeOrderPartial  2020-05-12  2020-06-02
474   France           Teleworking  2020-03-17  2020-05-10
476   France    TeleworkingPartial  2020-05-11  2020-10-28
477   France     WorkplaceClosures  2020-03-17  2020-05-11

[88 rows x 4 columns]

In [12]:
sorted_response = final_response.sort_values(
    ["Country", "date_start"], ascending=True)

sorted_response['date_start'] = pd.to_datetime(sorted_response['date_start']).dt.strftime('%m/%d/%Y')
sorted_response['date_end'] = pd.to_datetime(sorted_response['date_end']).dt.strftime('%m/%d/%Y')
sorted_response

     Country                     Response_measure  date_start    date_end
85   Belgium                       IndoorOver1000  03/10/2020  03/17/2020
92   Belgium                        MassGatherAll  03/10/2020  03/17/2020
111  Belgium                          Teleworking  03/10/2020  06/07/2020
69   Belgium                             ClosPrim  03/13/2020  05/17/2020
72   Belgium                           ClosPubAny  03/13/2020  05/03/2020
..       ...                                  ...         ...         ...
464   France  PrivateGatheringRestrictionsPartial  09/23/2020  10/28/2020
465   France         RegionalStayHomeOrderPartial  10/17/2020  10/28/2020
432   France                             ClosHigh  10/27/2020  01/24/2021
471   France                        StayHomeOrder  10/28/2020  12/14/2020
457   France                    NonEssentialShops  10/29/2020  11/27/2020

[88 rows x 4 columns]

In [11]:
sorted_response.to_csv("sorted_response.csv", index=False, header=True)